### ISSUE TITLE
Compilation errors (Ubuntu 16.04.3 LTS): './shtool': File exists

### ISSUE THREAD

**Issue by s-tikhomirov** [ivanpustogarov/bcclient#1]
When following the compilation instructions, on `ln -s $(which shtool)` I get:

```
ln: failed to create symbolic link './shtool': File exists
```
[see #2]
~~I assume this should not be a show-stopper and move on, but on first 'make' (in libbitcoin) I get:~~

```
utility/mnemonic.cpp: In function ‘const string libbitcoin::decode_mnemonic(const string_list&)’:
utility/mnemonic.cpp:1704:5: error: ‘cout’ is not a member of ‘std’
     std::cout << std::endl;
     ^
Makefile:603: recipe for target 'utility/mnemonic.lo' failed
make[1]: *** [utility/mnemonic.lo] Error 1
make[1]: Leaving directory '/home/sergei/Documents/research/code/bcclient/bcclient/libbitcoin/src'
Makefile:511: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by s-tikhomirov** [comment]
[see #2] ~~Solved by adding `#include<iostream>` to `/libbitcoin/src/utility/mnemonic.cpp` and also to `/main.cpp` (same error popped up on second `make`). Not sure this is the proper way though.~~

**Comment by ivanpustogarov** [comment]
I think it should two different issues: 1) symlink to shtool, 2) error with cout

**Comment by s-tikhomirov** [comment]
Ok, moved second issue to #2 .

**Comment by s-tikhomirov** [comment]
Actually, this one should not be closed: I still experience this issue. Not a huge problem though, as this is just a warning.
